/* eslint-disable max-len */
const genre = [
  { id: 1, name: 'Fantasy' },
  { id: 2, name: 'Supernatural' },
  { id: 3, name: 'Humorous' },
  { id: 4, name: 'Thriller' },
  { id: 5, name: 'Biography' },
  { id: 6, name: 'Cooking' },
  { id: 7, name: 'History' },
  { id: 8, name: 'Travel' },
  { id: 9, name: 'Crime' },
  { id: 10, name: 'Horror' },
  { id: 11, name: 'True Crime' },
  { id: 12, name: 'Social Sciences' },
  { id: 13, name: 'Criminology' },
  { id: 14, name: 'Spirituality' },
  { id: 15, name: 'Dystopian' },
  { id: 16, name: 'Adventure' },
  { id: 17, name: 'Romance' },
  { id: 18, name: 'Detective' },
  { id: 19, name: 'Mystery' },
  { id: 20, name: 'Historical Fiction' },
];
const book = [
  {
    title: 'Chainsaw Man, Vol. 1',
    author: 'Tatsuki Fujimoto',
    price: '9.29',
    text: 'Denji was a small-time devil hunter just trying to survive in a harsh world. After being killed on a job, he is revived by his pet devil Pochita and becomes something new and dangerous--Chainsaw Man!',
    rate: '5',
    cover: 'Chainman1.jpg',
    date: '01/01/2020',
    genre: [genre[0], genre[15]],
    status: 'Hardcover',
  },
  {
    title: 'Chainsaw Man, Vol. 2',
    author: 'Tatsuki Fujimoto',
    price: '9.99',
    text: 'Denji was a small-time devil hunter just trying to survive in a harsh world. After being killed on a job, he is revived by his pet devil Pochita and becomes something new and dangerous--Chainsaw Man!',
    rate: '5',
    cover: 'Chainman2.jpg',
    date: '01/01/2020',
    genre: [genre[0], genre[15]],
    status: 'Hardcover',
  },
  {
    title: 'Chainsaw Man, Vol. 3',
    author: 'Tatsuki Fujimoto',
    price: '15.49',
    text: 'Denji was a small-time devil hunter just trying to survive in a harsh world. After being killed on a job, he is revived by his pet devil Pochita and becomes something new and dangerous--Chainsaw Man!',
    rate: '5',
    cover: 'Chainman3.jpg',
    date: '01/02/2020',
    genre: [genre[0], genre[15]],
    status: 'Hardcover',
  },
  {
    title: 'Chainsaw Man, Vol. 4',
    author: 'Tatsuki Fujimoto',
    price: '9.29',
    text: 'Denji was a small-time devil hunter just trying to survive in a harsh world. After being killed on a job, he is revived by his pet devil Pochita and becomes something new and dangerous--Chainsaw Man!',
    rate: '5',
    cover: 'Chainman4.jpg',
    date: '01/03/2020',
    genre: [genre[0], genre[12]],
    status: 'Hardcover',
  },
  {
    title: 'Chainsaw Man, Vol. 5',
    author: 'Tatsuki Fujimoto',
    price: '8.70',
    text: 'Denji was a small-time devil hunter just trying to survive in a harsh world. After being killed on a job, he is revived by his pet devil Pochita and becomes something new and dangerous--Chainsaw Man!',
    rate: '5',
    cover: 'Chainman5.jpg',
    date: '01/04/2020',
    genre: [genre[0], genre[12]],
    status: 'Hardcover',
  },
  {
    title: 'Chainsaw Man, Vol. 6',
    author: 'Tatsuki Fujimoto',
    price: '15.29',
    text: 'Denji was a small-time devil hunter just trying to survive in a harsh world. After being killed on a job, he is revived by his pet devil Pochita and becomes something new and dangerous--Chainsaw Man!',
    rate: '5',
    cover: 'Chainman6.jpg',
    date: '01/05/2020',
    genre: [genre[3], genre[11]],
    status: 'Hardcover',
  },
  {
    title: 'Chainsaw Man, Vol. 7',
    author: 'Tatsuki Fujimoto',
    price: '16.60',
    text: 'Denji was a small-time devil hunter just trying to survive in a harsh world. After being killed on a job, he is revived by his pet devil Pochita and becomes something new and dangerous--Chainsaw Man!',
    rate: '5',
    cover: 'Chainman7.jpg',
    date: '01/06/2020',
    genre: [genre[3], genre[11]],
    status: 'Hardcover',
  },
  {
    title: 'Chainsaw Man, Vol. 8',
    author: 'Tatsuki Fujimoto',
    price: '9.29',
    text: 'Denji was a small-time devil hunter just trying to survive in a harsh world. After being killed on a job, he is revived by his pet devil Pochita and becomes something new and dangerous--Chainsaw Man!',
    rate: '5',
    cover: 'Chainman8.jpg',
    date: '01/07/2020',
    genre: [genre[0], genre[15]],
    status: 'Hardcover',
  },
  {
    title: 'Chainsaw Man, Vol. 9',
    author: 'Tatsuki Fujimoto',
    price: '7.39',
    text: 'Denji was a small-time devil hunter just trying to survive in a harsh world. After being killed on a job, he is revived by his pet devil Pochita and becomes something new and dangerous--Chainsaw Man!',
    rate: '5',
    cover: 'Chainman9.jpg',
    date: '01/08/2020',
    genre: [genre[0], genre[15]],
    status: 'Hardcover',
  },
  {
    title: 'Chainsaw Man, Vol. 10',
    author: 'Tatsuki Fujimoto',
    price: '10.29',
    text: 'Denji was a small-time devil hunter just trying to survive in a harsh world. After being killed on a job, he is revived by his pet devil Pochita and becomes something new and dangerous--Chainsaw Man!',
    rate: '5',
    cover: 'Chainman10.jpg',
    date: '01/09/2020',
    genre: [genre[0], genre[15]],
    status: 'Hardcover',
  },
  {
    title: 'Chainsaw Man, Vol. 11',
    author: 'Tatsuki Fujimoto',
    price: '11.99',
    text: 'Denji was a small-time devil hunter just trying to survive in a harsh world. After being killed on a job, he is revived by his pet devil Pochita and becomes something new and dangerous--Chainsaw Man!',
    rate: '5',
    cover: 'Chainman11.jpg',
    date: '01/10/2020',
    genre: [genre[0], genre[15]],
    status: 'Hardcover',
  },
  {
    title: 'Hell Bent',
    author: 'Leigh Bardugo',
    price: '27.89',
    text: 'Find a gateway to the underworld. Steal a soul out of hell. A simple plan, except people who make this particular journey rarely come back. But Galaxy "Alex" Stern is determined to break Darlington out of purgatory--even if it costs her a future at Lethe and at Yale.',
    rate: '5',
    cover: 'HellBent.jpg',
    date: '10/03/2020',
    genre: [genre[0], genre[10]],
    status: 'Hardcover',
  },
  // {
  //   title: 'Ninth House',
  //   author: 'Leigh Bardugo',
  //   price: '25.89',
  //   text: 'Galaxy "Alex" Stern is the most unlikely member of Yale\'s freshman class. Raised in the Los Angeles hinterlands by a hippie mom, Alex dropped out of school early and into a world of shady drug-dealer boyfriends, dead-end jobs, and much, much worse. ',
  //   rate: '5',
  //   cover: 'NinthHouse.jpg',
  //   date: '10/04/2020',
  //   genre: [genre[1], genre[18]],
  //   status: 'Paperback',
  // },
  // {
  //   title: 'It Ends with Us',
  //   author: 'Colleen Hoover',
  //   price: '27.99',
  //   text: "From the #1 New York Times bestselling author of It Starts with Us and All Your Perfects, a \"brave and heartbreaking novel that digs its claws into you and doesn't let go, long after you've finished it\" (Anna Todd, New York Times bestselling author) about a workaholic with a too-good-to-be-true romance can't stop thinking about her first love.",
  //   rate: '4',
  //   cover: 'ItEndswithUs.jpg',
  //   date: '10/05/2020',
  //   genre: [genre[16]],
  //   status: 'Paperback',
  // },
  // {
  //   title: 'Happy Place',
  //   author: 'Emily Henry',
  //   price: '27.89',
  //   text: 'A couple who broke up months ago pretend to still be together for their annual weeklong vacation with their best friends in this glittering and wise new novel from #1 New York Times bestselling author Emily Henry.',
  //   rate: '4',
  //   cover: 'HappyPlace.jpg',
  //   date: '01/01/2023',
  //   genre: [genre[16]],
  //   status: 'Paperback',
  // },
  // {
  //   title:
  //     "I Always Think It's Forever: A Love Story Set in Paris as Told by an Unreliable But Earnest Narrator",
  //   author: 'Timothy Goodman',
  //   price: '27.89',
  //   text: "A sweeping, unique graphic memoir about an artist's year abroad in Paris and how it gave way to an all-encompassing love affair and crushing heartbreak as he wrestled with trauma, masculinity, and the real possibility of hope.",
  //   rate: '5',
  //   cover: 'AlwaysThink.jpg',
  //   date: '10/11/2020',
  //   genre: [genre[4], genre[7]],
  //   status: 'Paperback',
  // },
  // {
  //   title: '40 Days of Dating: An Experiment',
  //   author: 'Timothy Goodman',
  //   price: '10.89',
  //   text: 'When New York-based graphic designers and long-time friends Timothy Goodman and Jessica Walsh found themselves single at the same time, they decided to try an experiment. The old adage says that it takes 40 days to change a habit--could the same be said for love? So they agreed to date each other for 40 days, record their experiences in questionnaires, photographs, videos, texts, and artworks, and post the material on a website they would create for this purpose.',
  //   rate: '3',
  //   cover: '40DaysofDating.jpg',
  //   date: '10/12/2021',
  //   genre: [genre[0], genre[1], genre[18]],
  //   status: 'Paperback',
  // },
  // {
  //   title:
  //     'Smitten Kitchen Keepers: New Classics for Your Forever Files: A Cookbook',
  //   author: 'Deb Perelman',
  //   price: '32.55',
  //   text: "NEW YORK TIMES BEST SELLER - A BON APPETIT BEST BOOK OF THE YEAR - The long-awaited new book from the best-selling and beloved author of The Smitten Kitchen Cookbook and Smitten Kitchen Every Day--a collection of essential recipes for meals you'll want to prepare again and again, from Cozy Chicken and Dumplings to Fettuccine with White Ragú, and from Chocolate Peanut Butter Cup Cookies to Strawberry Summer Stack Cake.",
  //   rate: '4',
  //   cover: 'SmittenKitchen.jpg',
  //   date: '10/05/2021',
  //   genre: [genre[5], genre[6], genre[7]],
  //   status: 'Paperback',
  // },
  // {
  //   title: 'Cookies Are Magic: Classic Cookies, Brownies, Bars, and More',
  //   author: 'Deb Perelman',
  //   price: '28.00',
  //   text: "Whether you are a chocolate chip or an old-fashioned gingersnap, this is the only cookie book you'll ever need -- from one of the best bakers of all time.",
  //   rate: '4',
  //   cover: 'CookiesAreMagic.jpg',
  //   date: '10/07/2020',
  //   genre: [genre[0], genre[1], genre[18]],
  //   status: 'Paperback',
  // },
  // {
  //   title:
  //     'Smitten Kitchen Every Day: Triumphant and Unfussy New Favorites: A Cookbook',
  //   author: 'Deb Perelman',
  //   price: '32.55',
  //   text: 'NEW YORK TIMES BEST SELLER - From the best-selling author of The Smitten Kitchen Cookbook--this everyday cookbook is "filled with fun and easy ... recipes that will have you actually looking forward to hitting the kitchen at the end of a long work day" (Bustle).',
  //   rate: '5',
  //   cover: 'SmittenKitchenEvery.jpg',
  //   date: '10/01/2023',
  //   genre: [genre[0], genre[1], genre[14]],
  //   status: 'Paperback',
  // },
  // {
  //   title: 'Shadow and Bone',
  //   author: 'Leigh Bardugo',
  //   price: '27.89',
  //   text: 'See the Grishaverse come to life on screen with Shadow and Bone, now a Netflix series.Enter the Grishaverse with Book One of the Shadow and Bone Trilogy by the #1 New York Times-bestselling author of Six of Crows and Crooked Kingdom.',
  //   rate: '3',
  //   cover: 'ShadowandBone.jpg',
  //   date: '13/01/2023',
  //   genre: [genre[0], genre[19]],
  //   status: 'Paperback',
  // },
  // {
  //   title: 'Siege and Storm',
  //   author: 'Leigh Bardugo',
  //   price: '36.99',
  //   text: "Soldier. Summoner. Saint. Alina Starkov's power has grown, but not without a price. She is the Sun Summoner--hunted across the True Sea, haunted by the lives she took on the Shadow Fold. But she and Mal can't outrun their enemies for long.",
  //   rate: '4',
  //   cover: 'SiegeandStorm.jpg',
  //   date: '15/01/2023',
  //   genre: [genre[3], genre[18]],
  //   status: 'Paperback',
  // },
  // {
  //   title: 'Ruin and Rising',
  //   author: 'Leigh Bardugo',
  //   price: '70.99',
  //   text: 'The Darkling rules from his shadow throne while a weakened Alina Starkov recovers from their battle under the dubious protection of the zealots who worship her as a Saint. Now her hopes lie with the magic of a long-vanished ancient creature and the chance that an outlaw prince still survives.',
  //   rate: '5',
  //   cover: 'RuinandRising.jpg',
  //   date: '19/01/2023',
  //   genre: [genre[9], genre[7]],
  //   status: 'Paperback',
  // },
  // {
  //   title: 'Six of Crows',
  //   author: 'Leigh Bardugo',
  //   price: '25.89',
  //   text: "Ketterdam: a bustling hub of international trade where anything can be had for the right price--and no one knows that better than criminal prodigy Kaz Brekker. Kaz is offered a chance at a deadly heist that could make him rich beyond his wildest dreams. But he can't pull it off alone. . . .",
  //   rate: '5',
  //   cover: 'SixofCrows.jpg',
  //   date: '18/01/2021',
  //   genre: [genre[4], genre[8]],
  //   status: 'Paperback',
  // },
  // {
  //   title: 'Crooked Kingdom',
  //   author: 'Leigh Bardugo',
  //   price: '12.99',
  //   text: "When you can't beat the odds, change the game.Kaz Brekker and his crew have just pulled off a heist so daring even they didn't think they'd survive. But instead of divvying up a fat reward, they're right back to fighting for their lives. Double-crossed and badly weakened, the crew is low on resources, allies, and hope. ",
  //   rate: '2',
  //   cover: 'CrookedKingdom.jpg',
  //   date: '10/01/2020',
  //   genre: [genre[10], genre[11], genre[18]],
  //   status: 'Paperback',
  // },
  // {
  //   title: 'Cyberpunk 2077: Blackout',
  //   author: 'Bartosz Sztybor',
  //   price: '29.89',
  //   text: "It hurts. Night City hurts. The suffering runs deep and the deeper one falls, the longer the self-prescribed dreams play. Fortune, hope, love--all made possible by DMS technology. A braindance repairman's daily encounters with his clients reveal the deterioration of the human mind and the desperation driving those to surrender to illusion. But not everyone desires a happy ending. Riddled with doubt, self-hatred, and guilt, he soon discovers the answer to pain . . . comes in a blackout.",
  //   rate: '3',
  //   cover: 'Cyberpunk.jpg',
  //   date: '10/12/2021',
  //   genre: [genre[5]],
  //   status: 'Paperback',
  // },
  // {
  //   title: 'All Talk',
  //   author: 'Bartosz Sztybor',
  //   price: '23.89',
  //   text: 'Rahim is a suburban kid like any other, a "good kid." Chilling with his boys, hearing the legends of "Immortal Al," the greatest gangster who ever lived, it\'s hard not to get starry eyed and soon, Rahim starts dreaming of becoming a kingpin, idolizing his local gangsters in the hopes of climbing their ranks.',
  //   rate: '1',
  //   cover: 'AllTalk.jpg',
  //   date: '10/10/2019',
  //   genre: [genre[17], genre[11]],
  //   status: 'Paperback',
  // },
  // {
  //   title: 'Cyberpunk 2077: You Have My Word',
  //   author: 'Bartosz Sztybor',
  //   price: '45.89',
  //   text: "A family is torn apart following an assignment from one of Night City's largest gangs. A new urban development proposal is being pushed through city council--a flagrant infraction on those safeguarded by the Valentinos gang--one to indulge the selfish and decadent lifestyles of the wealthy and displace the eldery in a historic housing block. ",
  //   rate: '1',
  //   cover: 'Cyberpunk2.jpg',
  //   date: '17/01/2020',
  //   genre: [genre[6]],
  //   status: 'Paperback',
  // },
  // {
  //   title: 'Cyberpunk 2077: Big City Dreams',
  //   author: 'Bartosz Sztybor',
  //   price: '33.89',
  //   text: 'Tasha and Mirek make a living for themselves stealing cyberware and indulging in parties and braindances. Tasha is rowdy and wild--she seeks to up her street cred to become the most famous gangster in the city. Mirek, on the other hand, is a calm introvert--he longs for something more--meaning, belonging, warmth.',
  //   rate: '4',
  //   cover: 'Cyberpunk3.jpg',
  //   date: '10/11/2021',
  //   genre: [genre[11], genre[1], genre[8]],
  //   status: 'Paperback',
  // },
  // {
  //   title: "Cyberpunk 2077: Where's Johnny",
  //   author: 'Bartosz Sztybor',
  //   price: '30.99',
  //   text: "Drunk, cynical, and stubborn journalist Thompson is working hard to wake up the populace--keeping their eyes and ears closed to the filth and corruption of corporate-run Night City is a choice and he's going to blow their self-prescribed diversions to pieces. Somebody nuked the headquarters of a major corporation.",
  //   rate: '2',
  //   cover: 'Cyberpunk4.jpg',
  //   date: '10/11/2020',
  //   genre: [genre[10], genre[15]],
  //   status: 'Paperback',
  // },
  // {
  //   title: 'Marvel Classic Black Light Collectible Poster Portfolio Volume 2',
  //   author: 'Marvel Entertainment',
  //   price: '30.59',
  //   text: 'The Marvel Super Heroes are back! Fans will light up with this second volume of the psychedelic, collectible portfolio featuring 12 frameable black-light posters of celebrated Marvel Comics characters, such as Spider-Man, Captain Marvel, Captain America, Doctor Strange, and Black Bolt, illustrated by legendary artists including Jack Kirby, John Romita Sr., Gil Kane, and more.',
  //   rate: '5',
  //   cover: 'MarvelClassic.jpg',
  //   date: '10/09/2020',
  //   genre: [genre[1], genre[11]],
  //   status: 'Hardcover',
  // },
  // {
  //   title: 'Spider-Man: Panel by Panel',
  //   author: 'Marvel Entertainment',
  //   price: '30.99',
  //   text: "Spider-Man first swung onto the comic book pages in August 1962 with the publication of Amazing Fantasy no. 15, created by Stan Lee and Steve Ditko and with cover art by Jack Kirby. Sixty years after the comic's publication, award-winning graphic designer Chip Kidd reimagines the iconic first story also told in The Amazing Spider-Man no. 1 from March 1963, using original vintage copies of both comic books to present these classic tales in a whole new way.",
  //   rate: '2',
  //   cover: 'SpiderMan.jpg',
  //   date: '10/08/2021',
  //   genre: [genre[10], genre[1]],
  //   status: 'Hardcover',
  // },
  // {
  //   title: 'Fantastic Four No. 1: Panel by Panel',
  //   author: 'Marvel Entertainment',
  //   price: '38.99',
  //   text: 'The first issue of Fantastic Four by legendary creators Stan Lee and Jack Kirby introduced fans to a now-iconic team of Super Heroes--Mister Fantastic, the Invisible Girl, the Human Torch, and the Thing--ushering in the modern Marvel Age of comics.',
  //   rate: '2',
  //   cover: 'Fantastic.jpg',
  //   date: '19/11/2020',
  //   genre: [genre[7], genre[4]],
  //   status: 'Hardcover',
  // },
  // {
  //   title: 'Attack on Titan Anthology',
  //   author: 'Scott Snyder',
  //   price: '36.99',
  //   text: "The manga megahit Attack on Titan, reinterpreted by some of comics' top talent! Featuring original stories by a long roster of comic superstars such as Scott Snyder (Batman, American Vampire), Gail Simone (Batgirl), Michael Avon Oeming (Powers), Paolo Rivera (Daredevil, Amazing Spider-Man), Cameron Stewart (Fight Club 2, Batgirl) and Faith Erin Hicks (The Adventures of Superhero Girl)!",
  //   rate: '5',
  //   cover: 'AttackonTitan.jpg',
  //   date: '13/11/2020',
  //   genre: [genre[16], genre[15]],
  //   status: 'Hardcover',
  // },
  // {
  //   title: 'Batman Vol. 2: The City of Owls',
  //   author: 'Scott Snyder',
  //   price: '39.99',
  //   text: 'For over a century, the Court of Owls has ruled Gotham City in secret--their reach inescapable, their power unstoppable. Until they battled the Batman.',
  //   rate: '1',
  //   cover: 'Batman.jpg',
  //   date: '11/11/2020',
  //   genre: [genre[13]],
  //   status: 'Hardcover',
  // },
  // {
  //   title: 'Justice League by Scott Snyder Book One',
  //   author: 'Scott Snyder',
  //   price: '31.99',
  //   text: 'Superman. Batman. Wonder Woman. Aquaman. The Flash. Cyborg. Green Lantern. Hawkgirl. Martian Manhunter. Nine heroes with powers as different as their personalities, but one thing in common: a dedication to defending the Earth.And they have never seen anything like this. They call it the Totality: the concentrated essence of the secret source of all things. When it crash-lands in the Nevada desert, everyone and everything that comes into contact with it comes out...changed. And power like that attracts the power-hungry. The mad, the merciless, the monstrous.',
  //   rate: '3',
  //   cover: 'JusticeLeague.jpg',
  //   date: '10/11/2020',
  //   genre: [genre[13], genre[11]],
  //   status: 'Paperback',
  // },
  // {
  //   title: 'We Have Demons',
  //   author: 'Scott Snyder',
  //   price: '30.99',
  //   text: 'Since the very dawn of man, legends have been told of the conflict between angel and demon-kind. Lam Lyle, a woman of science, dismissed these stories as just that -- fiction.But when the loss of a loved one leads to the discovery of a hulking, benevolent demon named Gus, Lam realizes that her life is about to undergo a dire new direction. With a newfound partner and awesome powers now at her disposal, our hero suddenly finds herself thrust into a climactic war of good and evil with no less than the fate of the world hanging in the balance...',
  //   rate: '2',
  //   cover: 'WeHaveDemons.jpg',
  //   date: '10/11/2020',
  //   genre: [genre[1]],
  //   status: 'Paperback',
  // },
  // {
  //   title: 'Zero Year-Dark City',
  //   author: 'Scott Snyder',
  //   price: '30.00',
  //   text: "Before the Batcave and Robin, the Joker and the Batmobile ... there was Zero Year. The Riddler has plunged Gotham City into darkness. How will a young Dark Knight bring his beloved hometown from the brink of chaos and madness and back into the light? From the critically acclaimed, New York Times #1 best-selling creative team of Scott Snyder and Greg Capullo, Batman Vol. 5: Zero Year--Dark City is the concluding volume to Batman's origin story, as you've never seen it before.",
  //   rate: '4',
  //   cover: 'ZeroYearDark.jpg',
  //   date: '10/11/2020',
  //   genre: [genre[3], genre[12]],
  //   status: 'Paperback',
  // },
  // {
  //   title: 'The Joker: Death of the Family',
  //   author: 'Scott Snyder',
  //   price: '12.99',
  //   text: "After having his face sliced off one year ago, The Joker makes his horrifying return in this new epic that features Batman's entire network of partners in crimefighting, including Batgirl, Catwoman, Nightwing, Robin, the Teen Titans and more. While The Joker threatens the very existence of Gotham City, these heroes--and villains--must find a way to survive.",
  //   rate: '4',
  //   cover: 'TheJoker.jpg',
  //   date: '10/11/2020',
  //   genre: [genre[10], genre[16]],
  //   status: 'Paperback',
  // },
  // {
  //   title: "L'Étoile Et Le Fouet",
  //   author: 'Frank Herbert',
  //   price: '15.99',
  //   text: 'Les couloirs calibans permettent de voyager presque instantanément entre les étoiles. Mais quelque chose le détraque. Tous ceux qui les ont récemment empruntés perdent la mémoire ou encore disparaissent dans le néant.',
  //   rate: '5',
  //   cover: 'Ltoile.jpg',
  //   date: '10/11/2020',
  //   genre: [genre[9], genre[7]],
  //   status: 'Paperback',
  // },
  // {
  //   title: 'Dune (Anniversary)',
  //   author: 'Frank Herbert',
  //   price: '17.99',
  //   text: 'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the "spice" melange, a drug capable of extending life and enhancing consciousness. Coveted across the known universe, melange is a prize worth killing for....',
  //   rate: '5',
  //   cover: 'Dune.jpg',
  //   date: '10/11/2020',
  //   genre: [genre[14], genre[17]],
  //   status: 'Paperback',
  // },
  // {
  //   title: 'The Collected Stories of Frank Herbert',
  //   author: 'Frank Herbert',
  //   price: '11.99',
  //   text: 'Frank Herbert, the New York Times bestselling author of Dune, is one of the most celebrated and commercially successful science fiction writers of all time. But while best known for originating the character of Paul Atreides and the desert world of Arrakis, Herbert was also a prolific writer of short fiction. His stories were published individually in numerous pulps and anthologies spanning decades, but never collected. Until now.',
  //   rate: '2',
  //   cover: 'TheCollected.jpg',
  //   date: '10/11/2020',
  //   genre: [genre[12]],
  //   status: 'Paperback',
  // },
];

export default book;
